# Generated by Django 3.0.4 on 2020-07-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_auto_20200703_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='b.Commande'),
            preserve_default=False,
        ),
    ]
